### ISSUE TITLE
Create route for checkin page

### ISSUE THREAD

**Issue by shashank-sharma** [dscatc/dscatc-webapp#1]
Right now Check-in page is not connected with routes, so create routes in urls.py and add appropriate path with views.

Hint: See how home page is getting rendered

**Comment by punndcoder28** [comment]
Hi. @shashank-sharma can I work on this? If my understanding is right I'll have to make changes to views.py and urls.py right? I don't need to create a check in page in html. Is this correct?

**Comment by punndcoder28** [comment]
I've created a PR #9 for this. Can you review and merge if everything is correct.

**Comment by shashank-sharma** [comment]
@punndcoder28 I reviewed your code, please check comments in PR

**Comment by punndcoder28** [comment]
I created a new PR #10 which made the changes as you recommended.

**Comment by shashank-sharma** [comment]
Resolved, thank you for your contribution
